name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check the cwd
        working-directory: ${{ env.working-directory }}
        run: pwd
      - run: npm install
      - run: npm test
        env:
          CI: true
